version: 1.2
workflows:
   -  name: Dipcall
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/dipcall.wdl
   -  name: BUSCO
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/busco.wdl
   -  name: Quast
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/quast.wdl
   -  name: Meryl
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/meryl.wdl
   -  name: Merqury
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/merqury.wdl
   -  name: Asmgene
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/asmgene.wdl
   -  name: YakAsmStats
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak.wdl
   -  name: YakAsmStatsnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak_no_qv.wdl
   -  name: Mash
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mash.wdl
   -  name: MaskAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mask_assembly.wdl
   -  name: FinalizeAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/finalizeAssembly.wdl
   -  name: findMitoContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/findMitoContigs.wdl
   -  name: ReadStats
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/read_stats.wdl
   -  name: FullQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/full_qc.wdl
   -  name: StandardQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc.wdl
   -  name: StandardQCnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_no_qv.wdl
   -  name: FilterHiFiAdapter
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/filter_hifi_adapter.wdl
   -  name: ExtractMitoContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/extractMitoContigs.wdl
   -  name: dropFastaContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/dropFastaContigs.wdl      
   -  name: TrioHifiasmAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly.wdl
   -  name: TrioHifiasmAssemblyYakInput
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly_yak_input.wdl
   -  name: YakNoStats
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/yak_no_stats.wdl
   -  name: PhasedGFAs2Fasta
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/gfatools.wdl
   -  name: StandardQCHaploid
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_haploid.wdl
   -  name: StandardQCHaploid
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/contamination.wdl

